import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export const metadata: Metadata = {
  title: "Create my Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      {/* Aplicamos um estilo simples no body apenas para o footer ficar sempre embaixo */}
      <body style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', margin: 0 }}>
        
        {/* 2. O Header fixo no topo de todas as páginas */}
        <Header/>

        {/* 3. A tag <main> que vai receber o conteúdo dinâmico */}
        <main style={{ flex: 1, padding: '20px' }}>
          {children} 
        </main>

        {/* 4. O Footer fixo no final de todas as páginas */}
        <Footer />

      </body>
    </html>
  )
}